//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiateText.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploisTemp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmploisTemp()
        {
            this.Realisations = new HashSet<Realisation>();
        }
    
        public int IdET { get; set; }
        public string Jour { get; set; }
        public System.TimeSpan HeureDebut { get; set; }
        public System.TimeSpan HeureFin { get; set; }
        public int Matricule { get; set; }
        public int NumeroGroupe { get; set; }
    
        public virtual Formateur Formateur { get; set; }
        public virtual Groupe Groupe { get; set; }
        public virtual Jour Jour1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Realisation> Realisations { get; set; }
    }
}
