//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiateText.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filiere
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Filiere()
        {
            this.ModuleFilieres = new HashSet<ModuleFiliere>();
        }
    
        public string CodeFiliere { get; set; }
        public string Nom { get; set; }
        public string CodeNiveau { get; set; }
    
        public virtual Niveau Niveau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleFiliere> ModuleFilieres { get; set; }
    }
}
