//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CiateText.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_cahier_texteEntities3 : DbContext
    {
        public db_cahier_texteEntities3()
            : base("name=db_cahier_texteEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Affectation> Affectations { get; set; }
        public virtual DbSet<DirectionRegionale> DirectionRegionales { get; set; }
        public virtual DbSet<EmploisTemp> EmploisTemps { get; set; }
        public virtual DbSet<Etablissement> Etablissements { get; set; }
        public virtual DbSet<Filiere> Filieres { get; set; }
        public virtual DbSet<Formateur> Formateurs { get; set; }
        public virtual DbSet<Groupe> Groupes { get; set; }
        public virtual DbSet<Jour> Jours { get; set; }
        public virtual DbSet<ModeFormation> ModeFormations { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleFiliere> ModuleFilieres { get; set; }
        public virtual DbSet<Niveau> Niveaux { get; set; }
        public virtual DbSet<Realisation> Realisations { get; set; }
        public virtual DbSet<Stagiaire> Stagiaires { get; set; }
        public virtual DbSet<TypeFormation> TypeFormations { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
